### ISSUE TITLE
Installitaion problem: Parse error, syntax error

### ISSUE THREAD

**Issue by ArmanJR** [AloPeyk/AloPeyk-WooCommerce-Plugin#5]
Error in installing this plugin on my localhost word press:

( ! ) Parse error: syntax error, unexpected '[' in C:\wamp\www\my_shop\wp-content\plugins\alopeyk-woocommerce-shipping\vendor\alopeyk\alopeyk-api-php\src\AloPeykApiHandler.php on line 300

conflicts? 🤔

**Comment by bijanmoudi** [comment]
It seems that it is a problem with your PHP version.
Since it originally comes from [AloPeykApiHandler.php](https://github.com/AloPeyk/AloPeyk-Api-PHP/blob/master/src/AloPeykApiHandler.php) laid in [ AloPeyk-Api-PHP](https://github.com/AloPeyk/AloPeyk-Api-PHP), it is better to report the issue there.

**Comment by bijanmoudi** [comment]
Issue can be resolved by updating server/hosting PHP version to at least 5.6.

**Comment by ArmanJR** [comment]
I've already updated php version and it's now working. Thanks
